Repository atk4/dsql, pull requests merged in 2020-06, with the labels that each got.

#206 Refactor exception constructor calls to not use array
  docs/advanced.rst
  src/Connection.php
  src/Expression.php
  src/Query.php
Labels: RTM

#210 Remove badly fixed phpdoc comment
  src/Expression.php
Labels: RTM

#211 Remove @throws by CS fixer
  .php_cs.dist
Labels: RTM

#212 Implement query->allowToWrapInParenthesis property
  src/Expression.php
  src/Query.php
  tests/QueryTest.php
Labels: RTM

#213 [refactor] introduce debug classes under new structure
  docs/advanced.rst
  docs/extensions.rst
  src/Connection.php
  src/Connection_Counter.php
  src/Connection_Dumper.php
  src/Debug/Profiler/Connection.php
  src/Debug/Stopwatch/Connection.php
  tests/ConnectionTest.php
Labels: RTM, refactor

#216 Expression::getDebugQuery() no longer accepts $html param
  README.md
  docs/expressions.rst
  src/Expression.php
  tests/ConnectionTest.php
  tests/ExpressionTest.php
  tests/QueryTest.php
  tests/RandomTest.php
  tests/WithDb/SelectTest.php
Labels: BC-break

#215 Rename classes - use NS instead of flat structure with "_"
  docs/advanced.rst
  docs/expressions.rst
  src/Connection.php
  src/Connection_Counter.php
  src/Connection_Dumper.php
  src/Connection_Oracle.php
  src/Connection_Oracle12.php
  src/Connection_PgSQL.php
  src/Connection_Proxy.php
  src/Debug/Profiler/Connection.php
  src/Debug/Stopwatch/Connection.php
  src/Expression_MySQL.php
  src/Mysql/Connection.php
  src/Mysql/Expression.php
  src/Mysql/Query.php
  src/Oracle/AbstractQuery.php
  src/Oracle/Connection.php
  src/Oracle/Query.php
  src/Oracle/Version12/Connection.php
  src/Oracle/Version12/Query.php
  src/Postgresql/Connection.php
  src/Postgresql/Query.php
  src/ProxyConnection.php
  src/Query.php
  src/Query_MySQL.php
  src/Query_Oracle.php
  src/Query_Oracle12c.php
  src/Query_Oracle_Abstract.php
  src/Query_PgSQL.php
  src/Query_SQLite.php
  src/Sqlite/Connection.php
  src/Sqlite/Query.php
  tests/ConnectionTest.php
  tests/OracleTest.php
  tests/QueryTest.php
  tests/RandomTest.php
  tests/WithDb/SelectTest.php
Labels: BC-break, in review, refactor

#219 Add testing with PHP 8.0
  .github/workflows/unit-tests.yml
  composer.json
  src/Expression.php
  src/Query.php
  tests/ExpressionTest.php
Labels: RTM
