Repository atk4/dsql, pull requests merged in 2020-07, with the labels that each got.

#224 Remove "See our "Awesome Queries" gallery" from README
  README.md
Labels: Documentation

#225 Use refactored TestCase::callProtected() method
  tests/ExpressionTest.php
  tests/QueryTest.php
Labels: RTM

#226 Fix PSR class/trait/method naming
  docs/advanced.rst
  src/Connection.php
  src/Expression.php
  src/Expressionable.php
  src/Oracle/Connection.php
  tests/ConnectionTest.php
  tests/ExpressionTest.php
Labels: RTM, refactor

#218 Add Connection classes registry (instead of hardcoded list)
  docs/advanced.rst
  docs/connection.rst
  src/Connection.php
  src/Debug/Profiler/Connection.php
  src/Debug/Stopwatch/Connection.php
  src/Mysql/Connection.php
  src/Oracle/Connection.php
  src/Oracle/Version12/Connection.php
  src/Postgresql/Connection.php
  src/Query.php
  src/Sqlite/Connection.php
  tests/ConnectionTest.php
Labels: RTM, enhancement, refactor

#228 Fix composer develop install issue
  .github/workflows/bundler.yml
  composer.json
Labels: RTM

#229 Fix composer.json formatting
  composer.json
Labels: RTM
