Repository atk4/dsql, pull requests merged in 2020-10, with the labels that each got.

#254 Add DBAL platform getter to Connection
  composer.json
  src/Connection.php
  src/Mssql/Connection.php
  src/Mysql/Connection.php
  src/Oracle/Connection.php
  src/Postgresql/Connection.php
  src/ProxyConnection.php
  src/Sqlite/Connection.php
  tests/ConnectionTest.php
  tests/WithDb/ConnectionTest.php
Labels: RTM

#261 Drop driverType property and debug connection classes
  .github/workflows/unit-tests.yml
  docs/advanced.rst
  docs/connection.rst
  docs/extensions.rst
  src/Connection.php
  src/Connection_Counter.php
  src/Connection_Dumper.php
  src/Connection_Oracle.php
  src/Connection_Oracle12.php
  src/Connection_PgSQL.php
  src/Connection_Proxy.php
  src/Debug/Profiler/Connection.php
  src/Debug/Stopwatch/Connection.php
  src/Expression_MySQL.php
  src/Mssql/Connection.php
  src/Mysql/Connection.php
  src/Oracle/Connection.php
  src/Oracle/Version12/Connection.php
  src/Postgresql/Connection.php
  src/ProxyConnection.php
  src/Query_MySQL.php
  src/Query_Oracle.php
  src/Query_Oracle12c.php
  src/Query_Oracle_Abstract.php
  src/Query_PgSQL.php
  src/Query_SQLite.php
  src/Sqlite/Connection.php
  tests/ConnectionTest.php
  tests/WithDb/ConnectionTest.php
  tests/WithDb/SelectTest.php
  tests/WithDb/TransactionTest.php
Labels: BC-break, RTM

#264 Do not escape/template in quoted SQL string literals/identifiers
  src/Expression.php
  tests/ExpressionTest.php
Labels: BC-break, RTM

#263 Refactor to not use reference properties
  src/Expression.php
Labels: RTM

#262 Use DBAL connection instead of PDO directly
  docs/advanced.rst
  docs/connection.rst
  docs/transactions.rst
  src/Connection.php
  src/Expression.php
  src/Mssql/Connection.php
  src/Mysql/Connection.php
  src/Oracle/Connection.php
  src/Oracle/Version12/Connection.php
  src/Postgresql/Connection.php
  src/ProxyConnection.php
  src/Sqlite/Connection.php
  tests/ConnectionTest.php
  tests/WithDb/SelectTest.php
  tests/WithDb/TransactionTest.php
Labels: BC-break, MAJOR, RTM

#265 Test using lowest deps
  .github/workflows/unit-tests.yml
  composer.json
Labels: RTM

#266 Query everything thru DBAL connection (to trigger DBAL hooks)
  src/Connection.php
  src/Expression.php
  tests/ConnectionTest.php
  tests/WithDb/SelectTest.php
  tests/WithDb/TransactionTest.php
Labels: RTM

#267 Fix CS/typo
  .github/workflows/unit-tests.yml
  tests/QueryTest.php
Labels: RTM

#268 [feature] introduce Expression escape constants
  docs/expressions.rst
  docs/queries.rst
  src/Expression.php
  src/Mssql/ExpressionTrait.php
  src/Query.php
  tests/ExpressionTest.php
  tests/QueryTest.php
Labels: BC-break

#271 Rename Expression::get() to Expression::getRows()
  README.md
  docs/expressions.rst
  docs/queries.rst
  docs/quickstart.rst
  src/Expression.php
  src/Oracle/Query.php
  tests/WithDb/SelectTest.php
Labels: BC-break, RTM
